### ISSUE TITLE
issue on yarn start

### ISSUE THREAD

**Issue by jbalatero** [Seikho/fullstack-starter#1]
Thank you for this. I am trying this out and when running yarn start this is what I got:

![image](https://user-images.githubusercontent.com/3615746/163660099-9a92fec5-0833-494e-b81d-59d6a86a2377.png)

everything is working though I just wonder if it was intentional.

**Comment by Seikho** [comment]
Hi,
Definitely not intentional. I thought I resolved that.
I'll sort it out.

Thanks

**Comment by Seikho** [comment]
@jbalatero 

It should now be fixed on the latest master. The service was failing to start when the build folder is empty. The `prvsrv:start` script will perform a TypeScript build before attempting to start to fix this.

**Comment by jbalatero** [comment]
Thanks
